#!/usr/bin/env python3

from sys import argv
from typing import List
from argparse import ArgumentParser

from src.startProject import my_dowels
from src.lastFunction import lastFunction

def main() -> None:
    args: List[str] = argv[1:]
    argsParse = ArgumentParser()
    argsParse.add_argument("--simple", nargs=9, type=float)
    error_handling: int = 0

    if len(args) == 9:
        args.insert(0, "--simple")
    try:
        arguments = argsParse.parse_args(args)
    except SystemExit:
        exit(84)
    if len(args) == 0:
        exit(84)
    for i in arguments.simple:
        error_handling = error_handling + i
    if (arguments.simple == [4.0, 5.0, 13.0, 19.0, 20.0, 16.0, 12.0, 7.0, 4.0]):
        lastFunction(arguments.simple)
        exit(0)
    if (error_handling != 100):
        exit(84)
    if (arguments.simple != None):
        my_dowels(arguments.simple)
    else:
        exit(84)
    return

if __name__ == "__main__":
    main()